### GET request to example server
POST http://3.35.71.206:4000/api/auth/signup
Content-Type: application/json

{
  "username": "test12",
  "password": "test123456"
}

###
POST http://3.35.71.206:4000/api/auth/duplicate
Content-Type: application/json

{
  "username" : "test13"
}


###
POST http://3.35.71.206:4000/api/auth/login
Content-Type: application/json

{
  "username" : "test1",
  "password": "test123456"
}

###
POST http://3.35.71.206:4000/api/auth/logout

