### GET request to example server
POST http://localhost:4000/api/bookmark/regist
Content-Type: application/json

{
  "userId": "8f8ac1a1-2cbd-4fab-bbcf-3b9a1fbfc32e",
  "recipeId": "633bafd-e788-4636-83b7-92b8ad4226dc"
}

###