### GET request to example server
POST http://3.35.71.206:4000/api/bookmark/regist
Content-Type: application/json

{
  "userId": "fb5e1c85-b89a-41f3-ab77-cbf5f4059543",
  "recipeId": "4e44bc81-fafb-4935-b88b-122ea5a229c4"
}

###
DELETE http://localhost:4000/api/bookmark/delete
Content-Type: application/json

{
  "userId": "a915fbd2-f96a-4e1f-aabf-20c96ac29043",
  "recipeId": "ef14776c-7208-4908-9093-fa9189b9de5b"
}