### GET request to example server
POST http://localhost:4000/api/recipe/regist
Content-Type: application/json

{
  "userId": "a915fbd2-f96a-4e1f-aabf-20c96ac29043",
  "title": "123456789",
  "thumbnail": "123456789",
  "description": "1234567890",
  "ingredients": [
    {
      "name": "123456789",
      "quantity": "123456789"
    },
    {
      "name": "123456789",
      "quantity": "123456789"
    }
  ],
  "instructions": [
    {
      "title": "123456789",
      "imgUrl": "123456789",
      "description": "1234567890"
    },
    {
      "title": "123456789",
      "imgUrl": "123456789",
      "description": "1234567890"
    }
  ]
}

###
GET http://localhost:4000/api/recipe/detail?recipeId=718ce567-6616-4b9f-a837-9e11d4bb63d7


###
PUT http://localhost:4000/api/recipe/update
Content-Type: application/json

{
  "recipeId": "718ce567-6616-4b9f-a837-9e11d4bb63d7",
  "userId": "a915fbd2-f96a-4e1f-aabf-20c96ac29043",
  "title": "12345678910",
  "thumbnail": "123456789abc",
  "description": "1234567890",
  "ingredients": [
    {
      "name": "123456789",
      "quantity": "123456789"
    },
    {
      "name": "123456789",
      "quantity": "123456789"
    }
  ],
  "instructions": [
    {
      "title": "123456789",
      "imgUrl": "123456789",
      "description": "1234567890"
    },
    {
      "title": "123456789",
      "imgUrl": "123456789",
      "description": "1234567890"
    }
  ]
}