### GET request to example server
POST http://localhost:4000/api/recipe/regist
Content-Type: application/json

{
  "userId": "8f8ac1a1-2cbd-4fab-bbcf-3b9a1fbfc32e",
  "title": "123456789",
  "thumbnail": "123456789",
  "description": "1234567890",
  "ingredients": [
    {
      "name": "123456789",
      "quantity": "123456789"
    },
    {
      "name": "123456789",
      "quantity": "123456789"
    }
  ],
  "instructions": [
    {
      "title": "123456789",
      "imgUrl": "123456789",
      "description": "1234567890"
    },
    {
      "title": "123456789",
      "imgUrl": "123456789",
      "description": "1234567890"
    }
  ]
}

###
GET http://localhost:4000/api/recipe/detail?recipeId=633bafd5-e788-4636-83b7-92b8ad4226dc

###
GET http://localhost:4000/api/recipe/recheck?page=1&pageSize=5&userId=a915fbd2-f96a-4e1f-aabf-20c96ac29043

###
PUT http://localhost:4000/api/recipe/update
Content-Type: application/json

{
  "recipeId": "633bafd5-e788-4636-83b7-92b8ad4226dc",
  "userId": "8f8ac1a1-2cbd-4fab-bbcf-3b9a1fbfc32e",
  "title": "12345678910",
  "thumbnail": "123456789abc",
  "description": "1234567890",
  "ingredients": [
    {
      "name": "123456789",
      "quantity": "123456789"
    },
    {
      "name": "123456789",
      "quantity": "123456789"
    }
  ],
  "instructions": [
    {
      "title": "123456789",
      "imgUrl": "123456789",
      "description": "1234567890"
    },
    {
      "title": "123456789",
      "imgUrl": "123456789",
      "description": "1234567890"
    }
  ]
}